language: c

script: asdf plugin-test docker-compose $TRAVIS_BUILD_DIR "docker-compose --version"

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

os:
  - linux
  - osx
