name: Main Workflow

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  # schedule:
  #   - cron: "0 0 * * 5"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.1
        with:
          command: docker-compose --version
          version: "1.29.2"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # this will fail...
      - name: asdf_plugin_test_2_0_0
        uses: asdf-vm/actions/plugin-test@v1.0.1
        continue-on-error: true
        with:
          command: docker-compose --version
          version: "2.0.0"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
